### PR TITLE
fix some translations

### PR DESCRIPTION
**Pull request by MageDelfador**

### CODE REVIEW

**Comment by CloudiDust** [comment]
Sorry for the late reply. Thanks!

**Comment by MageDelfador** [comment]
any idea when this will be part of wesnoth?

**Comment by CloudiDust** [comment]
@MageDelfador My original plan was to send updated translations to the wesnoth devs right before the release of version 1.16.11. (I expect it to be released in October.)

But of course, I could submit them now and this is what I am going to do.

It might take some days before the submissions get committed into the official repo.

**Comment by CloudiDust** [comment]
I have submitted the updated translations to the devs.

**Pull request merged**
