### PR TITLE
add help images

### PR DESCRIPTION
**Pull request by celerini**
Hi, I just want to utilize my experience and save your time, if you like the images.

### CODE REVIEW

**Comment by CloudiDust** [comment]
Sorry for the late reply.

Thanks!

**Comment by CloudiDust** [comment]
Very sorry that I missed both the notifications for this merge request and 1.16.3 string freeze. They got buried in a ton of product promotion mails.

Again, thanks very much!

**Comment by celerini** [comment]
It looks like you used squash & merge, which leads to an error in my local git:

error: The branch 'screenshots' is not fully merged.

If it is so, can you please use default merge next time, which saves my commits?

**Comment by CloudiDust** [comment]
Sorry for the inconvenience. I'll use normal merge next time.

**Pull request merged**
